name: Deploy Terraform Infrastructure

on:
  push:
    branches:
      - main
      - feature/*
    paths:
      - 'modules/**'
      - 'environments/**'
      - '.github/workflows/deploy-infra.yaml'
  pull_request:
    branches:
      - main

env:
  TF_VERSION: 1.6.4
  AWS_REGION: us-west-2
  TF_WORKING_DIR: environments

jobs:
  terraform:
    name: "Terraform Plan & Apply"
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    defaults:
      run:
        shell: bash
        working-directory: ${{ env.TF_WORKING_DIR }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_TERRAFORM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var-file=${{ inputs.environment }}.tfvars

      - name: Terraform Apply (Manual Approval)
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve -var-file=${{ inputs.environment }}.tfvars
