name: Deploy Terraform Infrastructure

on:
  push:
    branches:
      - main
      - feature/*
    paths:
      - 'modules/**'
      - 'environments/**'
      - '.github/workflows/deploy-infra.yaml'
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'dev'

env:
  TF_VERSION: 1.6.4
  AWS_REGION: us-west-2
  TF_WORKING_DIR: . 

jobs:
  terraform:
    name: "Terraform Plan & Apply"
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    defaults:
      run:
        shell: bash
        working-directory: ${{ env.TF_WORKING_DIR }}

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_TERRAFORM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Clear Terraform Cache
        run: rm -rf ~/.terraform.d/plugin-cache

      # Cache Terraform modules to speed up builds
      - name: Cache Terraform Modules
        uses: actions/cache@v3
        with:
          path: ~/.terraform.d
          key: terraform-${{ runner.os }}-${{ hashFiles('**/*.tf') }}
          restore-keys: |
            terraform-${{ runner.os }}-

      - name: Set Environment Variable
        id: env
        run: |
          ENVIRONMENT=${{ github.event.inputs.environment }}
          if [ -z "$ENVIRONMENT" ]; then
            ENVIRONMENT="dev"
          fi
          echo "ENVIRONMENT=$ENVIRONMENT" >> $GITHUB_OUTPUT



      # Terraform Init
      - name: Terraform Init
        run: terraform init

      # Terraform Format Check
      - name: Terraform Format
        run: terraform fmt -check -recursive

      # Terraform Validate
      - name: Terraform Validate
        run: terraform validate

      # Terraform Plan
      - name: Terraform Init
        run: terraform -chdir=environments/dev init

      - name: Terraform Plan
        run: terraform -chdir=environments/dev plan -var-file=dev.tfvars
